# Grammar specs using EBNF
# The scope I aim for:
# variables, two types, while loop, if else blocks, function
#
# TODO:
# - Define 'parameter' and 'argument' rules
# - Add 'function_call' into 'expression'
# - Build expression precedence (primary, unary, math, compare, logic)
# - Add missing operators: !=, <=, >=, !, unary -
# - Define root 'program' rule
# - (Optional) Add 'void' type


(* ========================================================================== *)
(* LAYER 0: DEFINED CHARACTERS                                               *)
(* ========================================================================== *)

digit  = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
letter = "a" | ... | "z" | "A" | ... | "Z";


(* ========================================================================== *)
(* LAYER 1: TERMINALS & TOKENS                                                *)
(* ========================================================================== *)

(* Literals *)
integer_literal = [ "+" | "-" ], digit, {digit};
boolean_literal = "true" | "false";
literal         = integer_literal | boolean_literal;

(* Types *)
type_keyword = "int" | "bool";

(* Keywords *)
if_keyword   = "if";
else_keyword = "else";
while_keyword = "while";
return_keyword = "return";
(* Assignment operator *)
assign_op = "=";

(* Arithmetic operators *)
add_op               = "+";
minus_op            = "-";
divide_op           = "/";
multiply_op         = "*";
first_order_math_op  = divide_op | multiply_op;
second_order_math_op = add_op | minus_op;

(* Comparative operators *)
equal_op             = "==";
greater_op           = ">";
smaller_op           = "<";
comparative_operator = equal_op | greater_op | smaller_op;

(* Boolean operators *)
and_op           = "&&";
or_op            = "||";
boolean_operator = and_op | or_op;

(* Grouping operators *)
open_scope  = "{";
close_scope = "}";
open_group  = "(";
close_group = ")";

(* Identifier *)
identifier = letter, {letter | digit | "_"};


(* ========================================================================== *)
(* LAYER 2: EXPRESSIONS                                                       *)
(* ========================================================================== *)
math_expression = ...
compare_expression = ...
logic_expression = asign_op, literal | identifier;
expression = logic_expression | compare_expression | math_expression;


(* ========================================================================== *)
(* LAYER 3: INSTRUCTIONS                                                      *)
(* ========================================================================== *)

primary_instruction  = expression, ";";
assign_instruction   = identifier, assign_op, expression, ";";
block_instruction    = open_scope, {instruction}, close_scope;
variable_declaration = type_keyword, identifier, [assign_op,expression], ";";
if_instruction       = if_keyword, open_group, expression, close_group, instruction, [else_keyword, instruction];
while_instruction    = while_keyword, open_group, expression, close_group, instruction;
return_instruction = return_keyword, [expression],";";

instruction = if_instruction | primary_instruction | variable_declaration | block_instruction | while_instruction | return_instruction| assign_instruction;


(* ========================================================================== *)
(* LAYER 4: FUNCTIONS & PROGRAM                                               *)
(* ========================================================================== *)

(* functions *)
argument_list = open_group,[argument, {",",argument}],close_group;
param_list = open_group, [parameter, {",",parameter}],close_group;
function_definition = type_keyword, identifier, param_list, instruction;
function_call = identifier, argument_list;
